; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
; platform = espressif32 @ 6.5.0
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM6  
monitor_port = COM6 
monitor_speed = 115200

lib_deps = 
  crankyoldgit/IRremoteESP8266 @ 2.9.0
