; https://docs.platformio.org/page/projectconf.html
; https://thingspeak.mathworks.com/

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM6  
monitor_port = COM6 
monitor_speed = 115200

lib_deps = 
  mathworks/ThingSpeak @ 2.1.1